TRANSLATIONS = {
    "🇬🇧": {
        "sidebar_title": "🔍 Crypto Cycle Analysis",
        "select_asset": "Select Asset",
        "settings": "⚙️ Settings",
        "api_key_label": "CoinGecko API Key (Optional)",
        "api_key_help": "Leave empty to use Yahoo Finance data (Free)",
        "source_label": "Data Source Priority",
        "nav_label": "Navigation",
        "nav_options": {
            "Dashboard": "Dashboard",
            "Cycle Analysis": "Cycle Analysis",
            "Price Prediction": "Price Prediction",
            "DCA Calculator": "DCA Calculator"
        },
        "data_source": "### Data Source",
        "source_coingecko": "Source: CoinGecko API",
        "source_yahoo": "Source: Yahoo Finance (Fallback)",
        "fetch_data": "Fetching {coin} Market Data...",
        "load_error": "Failed to load data for {coin}. Please try again later or check your API key.",
        
        # Dashboard
        "dash_title": "🚀 {coin} Cycle Dashboard",
        "current_price": "Current Price",
        "days_since_halving": "Days Since BTC Halving",
        "cycle_progress": "Cycle Progress (BTC)",
        "next_halving": "Next BTC Halving",
        "progress_bar_title": "### Current Cycle Progress (Anchored to BTC Halving)",
        "recent_price_title": "### Recent Price Action (Last 30 Days)",
        "chart_price_title": "{coin} Price - 30 Days",
        
        # Cycle Analysis
        "cycle_title": "🔄 Historical Cycle Analysis ({coin})",
        "cycle_info": "Analysis is anchored to Bitcoin Halving Dates to show market correlation.",
        "full_history_title": "### Full Price History & BTC Halving Events",
        "full_history_chart": "{coin} Price History",
        "log_scale_label": "Log Scale",
        "linear_scale_label": "Linear Scale",
        "overlay_title": "### Cycle Overlay Comparison",
        "overlay_desc": "Comparing price performance relative to the BTC halving date.",
        "overlay_chart": "Cycle Performance (Absolute Price USD)",
        "stats_title": "### Cycle Statistics",
        "col_cycle": "Cycle",
        "col_start_date": "Start Date",
        "col_high": "Cycle High ($)",
        "col_days_high": "Days to High",
        "col_low": "Cycle Low ($)",
        
        # Price Prediction
        "pred_title": "🔮 Price Prediction ({coin})",
        "pred_disclaimer": "DISCLAIMER: This is a statistical projection based on historical cycle patterns. NOT FINANCIAL ADVICE.",
        "pred_error": "Not enough historical data to generate predictions (Need at least data from Cycle 2 or 3).",
        "fan_title": "### Cycle Projection",
        "fan_desc": "Projection based on the growth patterns of previous cycles (Cycle 2 & 3), scaled to the current cycle's start price.",
        "legend_actual": "Actual Price",
        "legend_median": "Median Projection",
        "legend_range": "Range (Min/Max)",
        "fan_chart_title": "{coin} Price Projection (Based on Historical Cycles)",
        "levels_title": "### Key Projection Levels",
        "metric_low": "Projected Low (End of Cycle)",
        "metric_median": "Projected Median",
        "metric_high": "Projected High",
        
        # DCA Calculator
        "dca_title": "💰 DCA Strategy Backtest ({coin})",
        "dca_desc": "Simulate a Dollar Cost Averaging strategy on {coin}.",
        "dca_params": "Parameters",
        "input_amount": "Monthly Investment ($)",
        "input_start": "Start Date",
        "input_end": "End Date",
        "btn_run": "Run Backtest",
        "dca_error": "Not enough data for selected range.",
        "metric_invested": "Total Invested",
        "metric_value": "Portfolio Value",
        "metric_roi": "ROI",
        "metric_drawdown": "Max Drawdown",
        "dca_chart_title": "Portfolio Value vs Invested Amount",
        "dca_success": "Backtest Completed!"
    },
    "🇨🇳": {
        "sidebar_title": "🔍 加密货币周期分析",
        "select_asset": "选择资产",
        "settings": "⚙️ 设置",
        "api_key_label": "CoinGecko API Key (可选)",
        "api_key_help": "留空以使用 Yahoo Finance 数据（免费）",
        "source_label": "数据源优先级",
        "nav_label": "导航",
        "nav_options": {
            "Dashboard": "仪表盘",
            "Cycle Analysis": "周期分析",
            "Price Prediction": "价格预测",
            "DCA Calculator": "定投回测"
        },
        "data_source": "### 数据来源",
        "source_coingecko": "来源: CoinGecko API",
        "source_yahoo": "来源: Yahoo Finance (备用)",
        "fetch_data": "正在获取 {coin} 市场数据...",
        "load_error": "无法加载 {coin} 的数据。请稍后再试或检查您的 API Key。",
        
        # Dashboard
        "dash_title": "🚀 {coin} 周期仪表盘",
        "current_price": "当前价格",
        "days_since_halving": "距 BTC 减半天数",
        "cycle_progress": "周期进度 (BTC)",
        "next_halving": "下次 BTC 减半",
        "progress_bar_title": "### 当前周期进度 (锚定 BTC 减半)",
        "recent_price_title": "### 近期价格走势 (过去30天)",
        "chart_price_title": "{coin} 价格 - 30天",
        
        # Cycle Analysis
        "cycle_title": "🔄 历史周期分析 ({coin})",
        "cycle_info": "分析锚定比特币减半日期，以展示市场相关性。",
        "full_history_title": "### 全量历史价格与 BTC 减半事件",
        "full_history_chart": "{coin} 价格历史",
        "log_scale_label": "对数坐标 (Log)",
        "linear_scale_label": "线性坐标 (Linear)",
        "overlay_title": "### 周期叠加对比",
        "overlay_desc": "对比相对于 BTC 减半日期的价格表现。",
        "overlay_chart": "周期表现 (绝对价格 USD)",
        "stats_title": "### 周期统计",
        "col_cycle": "周期",
        "col_start_date": "开始日期",
        "col_high": "周期高点 ($)",
        "col_days_high": "达峰天数",
        "col_low": "周期低点 ($)",
        
        # Price Prediction
        "pred_title": "🔮 价格预测 ({coin})",
        "pred_disclaimer": "免责声明：这是基于历史周期模式的统计推演。不构成财务建议。",
        "pred_error": "历史数据不足以生成预测（至少需要周期 2 或 3 的数据）。",
        "fan_title": "### 周期推演",
        "fan_desc": "基于过往周期（周期 2 和 3）的增长模式，按当前周期起点价格进行推演。",
        "legend_actual": "实际价格",
        "legend_median": "中位数推演",
        "legend_range": "区间 (最低/最高)",
        "fan_chart_title": "{coin} 价格推演 (基于历史周期)",
        "levels_title": "### 关键推演点位",
        "metric_low": "推演低点 (周期末)",
        "metric_median": "推演中位数",
        "metric_high": "推演高点",
        
        # DCA Calculator
        "dca_title": "💰 定投策略回测 ({coin})",
        "dca_desc": "模拟对 {coin} 的定投 (DCA) 策略。",
        "dca_params": "参数设置",
        "input_amount": "每月投入金额 ($)",
        "input_start": "开始日期",
        "input_end": "结束日期",
        "btn_run": "运行回测",
        "dca_error": "所选范围内数据不足。",
        "metric_invested": "总投入",
        "metric_value": "持仓价值",
        "metric_roi": "投资回报率 (ROI)",
        "metric_drawdown": "最大回撤",
        "dca_chart_title": "持仓价值 vs 总投入",
        "dca_success": "回测完成！"
    },
    "🇯🇵": {
        "sidebar_title": "🔍 暗号資産サイクル分析",
        "select_asset": "銘柄選択",
        "settings": "⚙️ 設定",
        "api_key_label": "CoinGecko APIキー (任意)",
        "api_key_help": "空欄の場合、Yahoo Financeデータを使用します（無料）",
        "source_label": "データソース優先度",
        "nav_label": "ナビゲーション",
        "nav_options": {
            "Dashboard": "ダッシュボード",
            "Cycle Analysis": "サイクル分析",
            "Price Prediction": "価格予測",
            "DCA Calculator": "積立投資 (DCA)"
        },
        "data_source": "### データソース",
        "source_coingecko": "ソース: CoinGecko API",
        "source_yahoo": "ソース: Yahoo Finance (代替)",
        "fetch_data": "{coin} の市場データを取得中...",
        "load_error": "{coin} のデータを読み込めませんでした。後でもう一度試すか、APIキーを確認してください。",
        
        # Dashboard
        "dash_title": "🚀 {coin} サイクル・ダッシュボード",
        "current_price": "現在価格",
        "days_since_halving": "BTC半減期からの経過日数",
        "cycle_progress": "サイクル進捗 (BTC)",
        "next_halving": "次回BTC半減期",
        "progress_bar_title": "### 現在のサイクル進捗 (BTC半減期基準)",
        "recent_price_title": "### 直近の値動き (過去30日間)",
        "chart_price_title": "{coin} 価格 - 30日間",
        
        # Cycle Analysis
        "cycle_title": "🔄 過去のサイクル分析 ({coin})",
        "cycle_info": "市場の相関関係を示すため、ビットコインの半減期を基準に分析しています。",
        "full_history_title": "### 全価格履歴 & BTC半減期イベント",
        "full_history_chart": "{coin} 価格履歴",
        "log_scale_label": "対数スケール (Log)",
        "linear_scale_label": "線形スケール (Linear)",
        "overlay_title": "### サイクル重ね合わせ比較",
        "overlay_desc": "BTC半減期を基準とした価格パフォーマンスの比較。",
        "overlay_chart": "サイクル・パフォーマンス (絶対価格 USD)",
        "stats_title": "### サイクル統計",
        "col_cycle": "サイクル",
        "col_start_date": "開始日",
        "col_high": "最高値 ($)",
        "col_days_high": "最高値までの日数",
        "col_low": "最安値 ($)",
        
        # Price Prediction
        "pred_title": "🔮 価格予測 ({coin})",
        "pred_disclaimer": "免責事項：これは過去のサイクルパターンに基づく統計的な予測です。投資助言ではありません。",
        "pred_error": "予測を生成するための過去データが不足しています（少なくともサイクル2または3のデータが必要です）。",
        "fan_title": "### サイクル予測",
        "fan_desc": "過去のサイクル（サイクル2および3）の成長パターンに基づき、現在のサイクルの開始価格に合わせてスケーリングした予測。",
        "legend_actual": "実際の価格",
        "legend_median": "予測中央値",
        "legend_range": "範囲 (最小/最大)",
        "fan_chart_title": "{coin} 価格予測 (過去サイクルに基づく)",
        "levels_title": "### 主要な予測レベル",
        "metric_low": "予測安値 (サイクル末)",
        "metric_median": "予測中央値",
        "metric_high": "予測高値",
        
        # DCA Calculator
        "dca_title": "💰 積立投資 (DCA) バックテスト ({coin})",
        "dca_desc": "{coin} のドルコスト平均法 (DCA) 戦略をシミュレーションします。",
        "dca_params": "パラメータ設定",
        "input_amount": "月間投資額 ($)",
        "input_start": "開始日",
        "input_end": "終了日",
        "btn_run": "バックテスト実行",
        "dca_error": "選択された期間のデータが不足しています。",
        "metric_invested": "総投資額",
        "metric_value": "ポートフォリオ評価額",
        "metric_roi": "投資収益率 (ROI)",
        "metric_drawdown": "最大ドローダウン",
        "dca_chart_title": "ポートフォリオ評価額 vs 投資額",
        "dca_success": "バックテスト完了！"
    }
}
